type sizeTypes = {
  key?: number;
  size: 'sm' | 'lg' | 'wp' | 'ml' | 'xl' | 'md' | 'gt';
}[][];

const fc660c: sizeTypes = [
  [
    { key: 27, size: 'sm' },
    { key: 49, size: 'sm' },
    { key: 50, size: 'sm' },
    { key: 51, size: 'sm' },
    { key: 52, size: 'sm' },
    { key: 53, size: 'sm' },
    { key: 54, size: 'sm' },
    { key: 55, size: 'sm' },
    { key: 56, size: 'sm' },
    { key: 57, size: 'sm' },
    { key: 48, size: 'sm' },
    { key: 189, size: 'sm' },
    { key: 187, size: 'sm' },
    { key: 8, size: 'lg' },
    { size: 'wp' },
    { key: 45, size: 'sm' },
  ],
  [
    { key: 9, size: 'ml' },
    { key: 81, size: 'sm' },
    { key: 87, size: 'sm' },
    { key: 69, size: 'sm' },
    { key: 82, size: 'sm' },
    { key: 84, size: 'sm' },
    { key: 89, size: 'sm' },
    { key: 85, size: 'sm' },
    { key: 73, size: 'sm' },
    { key: 79, size: 'sm' },
    { key: 80, size: 'sm' },
    { key: 219, size: 'sm' },
    { key: 221, size: 'sm' },
    { key: 220, size: 'ml' },
    { size: 'wp' },
    { key: 46, size: 'sm' },
  ],
  [
    { key: 20, size: 'lg' },
    { key: 65, size: 'sm' },
    { key: 83, size: 'sm' },
    { key: 68, size: 'sm' },
    { key: 70, size: 'sm' },
    { key: 71, size: 'sm' },
    { key: 72, size: 'sm' },
    { key: 74, size: 'sm' },
    { key: 75, size: 'sm' },
    { key: 76, size: 'sm' },
    { key: 186, size: 'sm' },
    { key: 222, size: 'sm' },
    { key: 13, size: 'xl' },
    { size: 'wp' },
    { size: 'wp' },
    { size: 'wp' },
  ],
  [
    { key: 16, size: 'xl' },
    { key: 90, size: 'sm' },
    { key: 88, size: 'sm' },
    { key: 67, size: 'sm' },
    { key: 86, size: 'sm' },
    { key: 66, size: 'sm' },
    { key: 78, size: 'sm' },
    { key: 77, size: 'sm' },
    { key: 188, size: 'sm' },
    { key: 190, size: 'sm' },
    { key: 191, size: 'sm' },
    { key: 16, size: 'xl' },
    { key: 38, size: 'sm' },
    { size: 'wp' },
    { size: 'wp' },
  ],
  [
    { key: 17, size: 'md' },
    { key: 91, size: 'md' },
    { key: 18, size: 'md' },
    { key: 32, size: 'gt' },
    { key: 21, size: 'md' },
    { key: 25, size: 'md' },
    { key: 92, size: 'md' },
    { key: 37, size: 'sm' },
    { key: 40, size: 'sm' },
    { key: 39, size: 'sm' },
  ],
];

// eslint-disable-next-line import/prefer-default-export
export { fc660c };
